Repository Alkheemist/frontier-station-14, pull requests merged in 2025-01, with the labels that each got.

#2 test
  Content.Server/Medical/HealingSystem.cs
  Content.Server/_NF/Construction/Conditions/NFStrapEmpty.cs
  Resources/Changelog/Frontier.yml
  Resources/Locale/en-US/_NF/construction/conditions/strap-buckled.ftl
  Resources/Maps/_NF/POI/trade.yml
  Resources/Maps/_NF/POI/trademall.yml
  Resources/Maps/_NF/Shuttles/Shipment/basicshipment1.yml
  Resources/Prototypes/Entities/Clothing/Shoes/misc.yml
  Resources/Prototypes/Recipes/Construction/Graphs/furniture/seats.yml
  Resources/Prototypes/Recipes/Lathes/misc.yml
  Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/cart.yml
  Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_expeditions_xeno.yml
  Resources/Prototypes/_NF/Entities/Structures/Dispensers/condiments.yml
  Resources/Prototypes/_NF/Entities/Structures/Lighting/ground_lighting.yml
  Resources/Prototypes/_NF/Shipyard/Shipment/basicshipment1.yml
  Resources/_NF/migration.yml
Labels: C#, FTL, Map-Shuttle, Map-POI, No C#

#3 sprites step one
  Resources/Prototypes/_NF/Entities/Structures/Shipping/Shipping.yml
  Resources/Textures/_NF/Structures/Shipping/shippingbarrels.rsi/black.png
  Resources/Textures/_NF/Structures/Shipping/shippingbarrels.rsi/blue.png
  Resources/Textures/_NF/Structures/Shipping/shippingbarrels.rsi/gray.png
  Resources/Textures/_NF/Structures/Shipping/shippingbarrels.rsi/green.png
  Resources/Textures/_NF/Structures/Shipping/shippingbarrels.rsi/meta.json
  Resources/Textures/_NF/Structures/Shipping/shippingbarrels.rsi/red.png
  Resources/Textures/_NF/Structures/Shipping/shippingbarrels.rsi/white.png
  Resources/Textures/_NF/Structures/Shipping/shippingbarrels.rsi/yellow.png
  Resources/Textures/_NF/Structures/Shipping/shippingboxes.rsi/box1.png
  Resources/Textures/_NF/Structures/Shipping/shippingboxes.rsi/meta.json
  Resources/Textures/_NF/Structures/Shipping/shippingpallet.rsi/barrel_straps.png
  Resources/Textures/_NF/Structures/Shipping/shippingpallet.rsi/base.png
  Resources/Textures/_NF/Structures/Shipping/shippingpallet.rsi/crate_straps.png
  Resources/Textures/_NF/Structures/Shipping/shippingpallet.rsi/meta.json
Labels: No C#

#6 drag check refactor
  Content.Server/_NF/StationEvents/EventSystems/LinkedLifecycleGridSystem.cs
  Content.Server/_NF/StationEvents/Events/BluespaceErrorRule.cs
Labels: C#

#5 Console and Voucher
  Resources/Prototypes/_NF/Entities/Objects/Devices/Misc/ship_vouchers.yml
  Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers_shipyard.yml
Labels: C#, No C#

#7 Shipping permit sprite, and major freight rework
  Resources/Prototypes/_NF/Entities/Objects/Devices/Misc/ship_vouchers.yml
  Resources/Prototypes/_NF/Entities/Structures/Freight/freight.yml
  Resources/Prototypes/_NF/Entities/Structures/Shipping/Shipping.yml
  Resources/Textures/_NF/Objects/Misc/shipyard_voucher.rsi/meta.json
  Resources/Textures/_NF/Objects/Misc/shipyard_voucher.rsi/shipping.png
  Resources/Textures/_NF/Structures/Freight/freight_barrels.rsi/black.png
  Resources/Textures/_NF/Structures/Freight/freight_barrels.rsi/blue.png
  Resources/Textures/_NF/Structures/Freight/freight_barrels.rsi/gray.png
  Resources/Textures/_NF/Structures/Freight/freight_barrels.rsi/green.png
  Resources/Textures/_NF/Structures/Freight/freight_barrels.rsi/meta.json
  Resources/Textures/_NF/Structures/Freight/freight_barrels.rsi/red.png
  Resources/Textures/_NF/Structures/Freight/freight_barrels.rsi/white.png
  Resources/Textures/_NF/Structures/Freight/freight_barrels.rsi/yellow.png
  Resources/Textures/_NF/Structures/Freight/freight_boxes.rsi/box1.png
  Resources/Textures/_NF/Structures/Freight/freight_boxes.rsi/meta.json
  Resources/Textures/_NF/Structures/Freight/freight_pallet.rsi/barrel_straps.png
  Resources/Textures/_NF/Structures/Freight/freight_pallet.rsi/base.png
  Resources/Textures/_NF/Structures/Freight/freight_pallet.rsi/crate_straps.png
  Resources/Textures/_NF/Structures/Freight/freight_pallet.rsi/meta.json
Labels: No C#

#8 Gray? In my overcolored mix? Unthinkable
  Resources/Prototypes/_NF/Entities/Structures/Freight/freight.yml
  Resources/Textures/_NF/Structures/Freight/freight_barrels.rsi/meta.json
  Resources/Textures/_NF/Structures/Freight/freight_barrels.rsi/steel.png
Labels: No C#

#9 Spriting finishing and mapping
  Resources/Maps/_NF/POI/cargodepot.yml
  Resources/Maps/_NF/POI/cargodepotalt.yml
  Resources/Maps/_NF/Shuttles/Shipment/basicshipment1.yml
  Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/shippingvend.yml
  Resources/Prototypes/_NF/Entities/Structures/Freight/freight.yml
  Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers_shipyard.yml
  Resources/Prototypes/_NF/Entities/Structures/Machines/vending_machines.yml
  Resources/Prototypes/_NF/Shipyard/Shipment/basicshipment1.yml
  Resources/Textures/_NF/Structures/Machines/VendingMachines/shippingvend.rsi/meta.json
  Resources/Textures/_NF/Structures/Machines/VendingMachines/shippingvend.rsi/normal-unshaded.png
  Resources/Textures/_NF/Structures/Machines/computers.rsi/meta.json
  Resources/Textures/_NF/Structures/Machines/computers.rsi/shipyard_shipping.png
Labels: Map-Shuttle, Map-POI, No C#

#10 spriting
  Resources/Prototypes/_NF/Entities/Structures/Machines/portable_pump.yml
  Resources/Textures/_NF/Structures/Machines/portable_pump.rsi/base.png
  Resources/Textures/_NF/Structures/Machines/portable_pump.rsi/meta.json
  Resources/Textures/_NF/Structures/Machines/portable_pump.rsi/powered.png
  Resources/Textures/_NF/Structures/Machines/portable_pump.rsi/pumping.png
  Resources/Textures/_NF/Structures/Machines/portable_pump.rsi/voiding.png
Labels: No C#
